### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by robert-chiodi** [desjardi/NGA2#25]
I would like to help you out by creating a spack-repo for NGA2 to make it much much easier for everyone to build it. Are there instructions anywhere now for how it is currently built?

**Comment by desjardi** [comment]
[nga2_intallation.pdf](https://github.com/desjardi/NGA2/files/10513962/nga2_intallation.pdf)

Sorry it took forever to get back to you - here's a fairly up-to-date set of build instructions.
Thanks!

**Comment by robert-chiodi** [comment]
No problem. Thanks for the instructions, I'll take a look and play around with spack a bit.
