### ISSUE TITLE
In the 'shock_water_cylinder' example, shock sensor (sl_x, sl_y, sl_z) does not capture the entire shock

### ISSUE THREAD

**Issue by JasonRabinovitch** [desjardi/NGA2#38]
Apologies if I am misinterpreting the data, but when fs%sl_x, fs%sl_y, and fs%sl_z are added to the output, it does not appear as if the shock sensor (and the switch to the semi-lagrangian scheme) is picking up the entire normal shock that is propagating from left to right. The air/water interface is captured, but there is a "gap" in the shock (see image below) at t~= 1e-5 s. We will keep looking into this, but just wanted to document it here as well. Simulation is being run with all of the default parameters specified in the shock_water_cylinder example input file.

![sl_x](https://github.com/desjardi/NGA2/assets/44269994/20cccf19-62ad-4d6f-ba1f-fef00e7cd50e)
![grho](https://github.com/desjardi/NGA2/assets/44269994/4166a7c0-f893-4656-b3cd-045c223e13a9)

**Comment by AJSayad** [comment]
To test and correct this, the shock sensor weight was adjusted (shs_wt in mast_class.f90) to track the shock fully through the domain on a uniform mesh (dx=dy=dz). The value of dz was then changed to be much greater than dx and dy, this then activated the shock sensor throughout the entire domain indicating that the sensor is using the largest mesh dimension. Then the shock sensor (mast_class.f90 line 1320) was changed from using min() to max() in which the full shock was tracked through the entire domain. In the originally coded sensor, the 'min()' would use the largest mesh dimension, but with the updated sensor 'max()' uses the minimum mesh dimension as stated by equation (34).

**Comment by JasonRabinovitch** [comment]
This issue is hopefully corrected with pull request #42
