### ISSUE TITLE
Error when installing IRL

### ISSUE THREAD

**Issue by giannis-bagkeris** [desjardi/NGA2#52]
Hi - I am getting the following errors when installing the interface reconstruction library - any suggestions?

![Screenshot from 2024-08-05 07-08-12c](https://github.com/user-attachments/assets/7e325728-13bf-4c0c-bb07-c98e0c4e43ca)

**Comment by fabienevrard** [comment]
Hello @giannis-bagkeris, what version of GCC are you using to compile IRL? It needs to support the C++17 standard to be able to compile the `if constexpr` statements.

**Comment by giannis-bagkeris** [comment]
Hi @fabienevrard. Thanks for your response. The GCC version I am using is 5.4.0 on Ubuntu 16.04.

**Comment by fabienevrard** [comment]
Yes that's too old (`if constexpr` has only been supported since GCC 7). You have two options:
1. Use a more recent version of GCC.
2. Checkout an older version of IRL that only requires the C++14 standard.

**Comment by giannis-bagkeris** [comment]
Thank you!
